---
include:
  - board: nice_nano_v2
    shield: eyelash_sofle_left nice_view
    snippet: zmk-usb-logging
    cmake-args: >-
      -DBUILD_VERSION=$(if [ "${GITHUB_REF_TYPE}" = "tag" ]; then echo "${GITHUB_REF_NAME}"; else echo "${GITHUB_SHA}" | cut -c1-8; fi)
  - board: nice_nano_v2
    shield: eyelash_sofle_right nice_view_infos
    snippet: zmk-usb-logging
    cmake-args: >-
      -DBUILD_VERSION=$(if [ "${GITHUB_REF_TYPE}" = "tag" ]; then echo "${GITHUB_REF_NAME}"; else echo "${GITHUB_SHA}" | cut -c1-8; fi)
  - board: nice_nano_v2
    shield: eyelash_sofle_left nice_view
    snippet: zmk-usb-logging;studio-rpc-usb-uart
    cmake-args: >-
      -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
      -DBUILD_VERSION=$(if [ "${GITHUB_REF_TYPE}" = "tag" ]; then echo "${GITHUB_REF_NAME}"; else echo "${GITHUB_SHA}" | cut -c1-8; fi)
    artifact-name: eyelash_sofle_studio_left
  - board: nice_nano_v2
    shield: settings_reset
    snippet: zmk-usb-logging
    cmake-args: >-
      -DBUILD_VERSION=$(if [ "${GITHUB_REF_TYPE}" = "tag" ]; then echo "${GITHUB_REF_NAME}"; else echo "${GITHUB_SHA}" | cut -c1-8; fi)
