manifest:
  defaults:
    revision: v0.3

  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
      # Additional modules containing boards/shields/custom code can be listed here as well.
      # See:
      # - https://zmk.dev/docs/features/modules
      # - https://docs.zephyrproject.org/3.5.0/develop/west/manifest.html#projects
    - name: urob
      url-base: https://github.com/urob
    - name: gpeye
      url-base: https://github.com/GPeye
    - name: ssbb
      url-base: https://github.com/ssbb
    - name: ebottacin
      url-base: https://github.com/ebottacin
  projects:
    - name: zmk-tri-state
      remote: urob
    - name: zmk-auto-layer
      remote: urob
    - name: zmk-listeners
      remote: ssbb
      revision: v1
    - name: zmk-caps-lock-events
      remote: ebottacin
      revision: main
    - name: zmk-info-widget
      remote: ebottacin
      revision: main
    - name: zmk-dynamic-logging
      remote: ebottacin
      repo-path: zmk_dynamic-logging
      revision: main
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
  self:
    path: boards
